# =============================================================================
# Build configuration options for Cortex-M
# =============================================================================

[build]
target = "thumbv8m.main-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nrf9160_xxaa" # runner specific to nrf9160. Replace this with probe-run option for your board.
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]